/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://sh3at5nlsnhbjmw5s5xl5sjd4e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-z45a3d4z6bfujongcwdtqkorye",
    "aws_cognito_identity_pool_id": "us-east-1:ed2d246f-deed-4741-89da-5afad22b410c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4OEHQYPdf",
    "aws_user_pools_web_client_id": "78aemqdknm39vjj41592jup5pc",
    "oauth": {},
    "aws_user_files_s3_bucket": "retail9765318dece64d78837883e645fe092b173217-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
